

global  HEAD_YAW,HEAD_PITCH,L_SHOULDER_PITCH,L_SHOULDER_ROLL,L_ELBOW_YAW,L_ELBOW_ROLL,\
            L_WRIST_YAW,L_HAND,L_HIP_YAW_PITCH,L_HIP_ROLL,L_HIP_PITCH,L_KNEE_PITCH,L_ANKLE_PITCH,\
            L_ANKLE_ROLL,R_HIP_YAW_PITCH,R_HIP_ROLL,R_HIP_PITCH,R_KNEE_PITCH,R_ANKLE_PITCH,\
            R_ANKLE_ROLL,R_SHOULDER_PITCH,R_SHOULDER_ROLL,R_ELBOW_YAW,R_ELBOW_ROLL,\
            R_WRIST_YAW,R_HAND

HEAD_YAW=0
HEAD_PITCH =1
L_SHOULDER_PITCH=2
L_SHOULDER_ROLL=3
L_ELBOW_YAW=4
L_ELBOW_ROLL=5
L_WRIST_YAW=6
L_HAND=7
L_HIP_YAW_PITCH=8
L_HIP_ROLL=9
L_HIP_PITCH=10
L_KNEE_PITCH=11
L_ANKLE_PITCH=12
L_ANKLE_ROLL=13
R_HIP_YAW_PITCH=14
R_HIP_ROLL=15
R_HIP_PITCH=16
R_KNEE_PITCH=17
R_ANKLE_PITCH=18
R_ANKLE_ROLL=19
R_SHOULDER_PITCH=20
R_SHOULDER_ROLL=21
R_ELBOW_YAW=22
R_ELBOW_ROLL=23
R_WRIST_YAW=24
R_HAND=25
    

global MotorCommand 
MotorCommand = [0 for x in range(26)]

   